before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - npm run build &
  - npm run server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 5
 
script:
  - "npm test"

  
language: node_js
node_js:
  - "6.6.0"
