before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - node_modules/.bin/includejs build.js import &
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox -v more &
  - firefox http://localhost:1111/capture &
  - sleep 5
 
script:
  - "npm test"
 
language: node_js
 
node_js:
  - 0.8.9