addons:
  firefox: "24.0"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - node_modules/.bin/atma build.js import &
  - node_modules/.bin/atma server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 5
 
script:
  - "npm test"

  
language: node_js
 
node_js:
  - 0.8.9